### ISSUE TITLE
integrate with termstyle

### ISSUE THREAD

**Issue by vitiral** [cetra3/lorikeet#1]
> This was brought up [on reddit](https://www.reddit.com/r/rust/comments/7xxigs/lorikeet_06_update_a_rust_based_cli_app_for/dud852q/?context=3)

I would like to open a PR to integrate this framework with `termstyle`. `termstyle` is still very young, so I am completely open to any API changes you feel should be made.

Also, I plan on adding cross-platform color support for termstyle in the future, probably with `crossterm` (in case that worries you).

**Comment by cetra3** [comment]
One question I'd have is what you see the tests looking like, do you have any examples that might help clarify how `termstyle` could be used.

At the moment I am aiming to keep it as cross platform as possible (lorikeet does run on windows, but obviously needs [bash installed](https://docs.microsoft.com/en-us/windows/wsl/install-win10) for those test types).  So I think `crossterm` would be awesome to use for that reason.

**Comment by cetra3** [comment]
The new version is using the `colored` crate, due to an issue I had with the previous lib.

Let me know if you're still keen to submit a PR for this, and I will reopen this issue!
