### ISSUE TITLE
Is there a way to disable SSL verification?

### ISSUE THREAD

**Issue by alexgenco** [cetra3/lorikeet#5]
We have cases where we would like to run smoke tests against local services, which use self-signed certificates. Is there a way to either disable SSL verification or specify an alternate CA?

Enjoying this tool so far!

**Comment by alexgenco** [comment]
I dug into `openssl-probe` and found it supports the `SSL_CERT_FILE` env var. Still curious about being able to disable it entirely though

**Comment by cetra3** [comment]
The `http` step uses the reqwest crate which looks like it has support for turning it off: https://docs.rs/reqwest/0.10.4/reqwest/struct.ClientBuilder.html#method.danger_accept_invalid_certs

Probably just need to add it as an option in http, which shouldn't be too hard!

**Comment by alexgenco** [comment]
Figured I'd give it a go: https://github.com/cetra3/lorikeet/pull/6
